// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRujfNw8XNTKxyeyQu7XNR78DMGl2pWE',
    appId: '1:268424911658:android:6459b32f6c3991c37b9c53',
    messagingSenderId: '268424911658',
    projectId: 'geneza-app-33ef3',
    storageBucket: 'geneza-app-33ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAKYXRR1GYgRykZb1K7OdV183icLyb-M',
    appId: '1:268424911658:ios:32747d4a9b25897b7b9c53',
    messagingSenderId: '268424911658',
    projectId: 'geneza-app-33ef3',
    storageBucket: 'geneza-app-33ef3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCslmMjnH_njXaL6X43624g3Loyxxv-Cac',
    appId: '1:268424911658:web:4b4682aaec3762687b9c53',
    messagingSenderId: '268424911658',
    projectId: 'geneza-app-33ef3',
    authDomain: 'geneza-app-33ef3.firebaseapp.com',
    storageBucket: 'geneza-app-33ef3.firebasestorage.app',
    measurementId: 'G-B6KCCD1PGB',
  );

}